import os
import sys
import json
import re
import jsonschema

# --- Configuration ---
# Assuming this script is in protocols/testing/, the root is two levels up.
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.append(ROOT_DIR)
SOURCE_DIR = os.path.dirname(__file__)
TARGET_FILE = os.path.join(SOURCE_DIR, "AGENTS.md")
SCHEMA_FILE = os.path.join(ROOT_DIR, "protocols", "protocol.schema.json")

from tooling.build_utils import find_files, load_schema, sanitize_markdown

DISCLAIMER_TEMPLATE = """\
# ---
# DO NOT EDIT THIS FILE DIRECTLY.
# This file is programmatically generated by the `build.py` script in this directory.
# All changes to agent protocols must be made in the source files
# located in the `{source_dir_name}/` directory.
#
# This file contains the compiled protocols in a human-readable Markdown format,
# with machine-readable JSON definitions embedded.
# ---
"""

def compile_module():
    """Compiles the protocol files in this directory into a single AGENTS.md."""
    print(f"--- Starting Protocol Compilation for Testing Module ---")
    print(f"Source directory: {SOURCE_DIR}")
    print(f"Target file: {TARGET_FILE}")

    schema = load_schema(SCHEMA_FILE)
    if not schema:
        return

    all_md_files = sorted([os.path.join(SOURCE_DIR, f) for f in find_files(".protocol.md", base_dir=SOURCE_DIR, recursive=False)])
    all_json_files = sorted([os.path.join(SOURCE_DIR, f) for f in find_files(".protocol.json", base_dir=SOURCE_DIR, recursive=False)])

    disclaimer = DISCLAIMER_TEMPLATE.format(source_dir_name=os.path.basename(SOURCE_DIR))
    final_content = [disclaimer]

    for file_path in all_md_files:
        with open(file_path, "r") as f:
            content = f.read()
            sanitized_content = sanitize_markdown(content)
            final_content.append(sanitized_content)
        final_content.append("\n---\n")

    for file_path in all_json_files:
        try:
            with open(file_path, "r") as f:
                protocol_data = json.load(f)
            jsonschema.validate(instance=protocol_data, schema=schema)
            json_string = json.dumps(protocol_data, indent=2)
            md_json_block = f"```json\n{json_string}\n```\n"
            final_content.append(md_json_block)
            final_content.append("\n---\n")
        except json.JSONDecodeError:
            print(f"Warning: Could not decode JSON from {file_path}", file=sys.stderr)
        except jsonschema.ValidationError as e:
            print(f"Warning: Schema validation failed for {file_path}: {e.message}", file=sys.stderr)

    final_output_string = "\n".join(final_content)
    temp_target_file = TARGET_FILE + ".tmp"
    with open(temp_target_file, "w") as f:
        f.write(final_output_string)
    os.rename(temp_target_file, TARGET_FILE)
    print(f"Successfully compiled AGENTS.md for testing module at {TARGET_FILE}")

if __name__ == "__main__":
    compile_module()
