import os
import sys
import json
import re
import jsonschema

# --- Configuration ---
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SOURCE_DIR = os.path.dirname(__file__)
TARGET_FILE = os.path.join(SOURCE_DIR, "AGENTS.md")
SCHEMA_FILE = os.path.join(ROOT_DIR, "protocols", "protocol.schema.json")

DISCLAIMER_TEMPLATE = """\
# ---
# DO NOT EDIT THIS FILE DIRECTLY.
# This file is programmatically generated by the `build.py` script in this directory.
# All changes to agent protocols must be made in the source files
# located in the `{source_dir_name}/` directory.
#
# This file contains the compiled protocols in a human-readable Markdown format,
# with machine-readable JSON definitions embedded.
# ---
"""

# --- Utility Functions (adapted from root compiler) ---

def find_files(pattern, base_dir=".", recursive=True):
    """Finds files matching a pattern in a directory."""
    if recursive:
        return [
            os.path.join(dp, f)
            for dp, dn, filenames in os.walk(base_dir)
            for f in filenames
            if f.endswith(pattern)
        ]
    else:
        return [
            f
            for f in os.listdir(base_dir)
            if os.path.isfile(os.path.join(base_dir, f)) and f.endswith(pattern)
        ]

def load_schema(schema_file):
    """Loads the JSON schema from a file."""
    try:
        with open(schema_file, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Error: Schema file not found at {schema_file}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from schema file at {schema_file}", file=sys.stderr)
        sys.exit(1)

def sanitize_markdown(content):
    """Removes potentially unsafe constructs from Markdown."""
    content = re.sub(r"<script.*?>.*?</script>", "", content, flags=re.IGNORECASE | re.DOTALL)
    content = re.sub(r" on\w+=\".*?\"", "", content, flags=re.IGNORECASE)
    content = re.sub(r"<<<SENSITIVE_INSTRUCTIONS>>>.*<<<SENSITIVE_INSTRUCTIONS>>>", "", content, flags=re.DOTALL)
    return content

# --- Core Compilation Logic ---

def compile_module():
    """Compiles the protocol files in this directory into a single AGENTS.md."""
    print(f"--- Starting Protocol Compilation for Guardian Module ---")
    print(f"Source directory: {SOURCE_DIR}")
    print(f"Target file: {TARGET_FILE}")

    schema = load_schema(SCHEMA_FILE)
    if not schema:
        return

    all_json_files = sorted([os.path.join(SOURCE_DIR, f) for f in find_files(".protocol.json", base_dir=SOURCE_DIR, recursive=False)])

    disclaimer = DISCLAIMER_TEMPLATE.format(source_dir_name=os.path.basename(SOURCE_DIR))
    final_content = [disclaimer]

    for file_path in all_json_files:
        try:
            with open(file_path, "r") as f:
                protocol_data = json.load(f)
            jsonschema.validate(instance=protocol_data, schema=schema)
            json_string = json.dumps(protocol_data, indent=2)
            md_json_block = f"```json\n{json_string}\n```\n"
            final_content.append(md_json_block)
            final_content.append("\n---\n")
        except json.JSONDecodeError:
            print(f"Warning: Could not decode JSON from {file_path}", file=sys.stderr)
        except jsonschema.ValidationError as e:
            print(f"Warning: Schema validation failed for {file_path}: {e.message}", file=sys.stderr)

    final_output_string = "\n".join(final_content)
    temp_target_file = TARGET_FILE + ".tmp"
    with open(temp_target_file, "w") as f:
        f.write(final_output_string)
    os.rename(temp_target_file, TARGET_FILE)
    print(f"Successfully compiled AGENTS.md for guardian module at {TARGET_FILE}")

if __name__ == "__main__":
    compile_module()
