import yaml
import jsonschema
import sys
from build_utils import sanitize_markdown

DISCLAIMER_TEMPLATE = """\
# ---
# DO NOT EDIT THIS FILE DIRECTLY.
# This file is programmatically generated by the unified protocol compiler.
# All changes to agent protocols must be made in the source files
# located in the `{source_dir_name}/` directory.
#
# This file contains the compiled protocols in a human-readable Markdown format,
# with machine-readable YAML definitions embedded.
# ---
"""

def generate_agents_md_content(module_name, md_files_content, yaml_files_content, schema):
    """
    Generates the content for an AGENTS.md file.
    """
    disclaimer = DISCLAIMER_TEMPLATE.format(source_dir_name=module_name)
    final_content = [disclaimer]

    for content in md_files_content:
        sanitized_content = sanitize_markdown(content)
        final_content.append(sanitized_content)
        final_content.append("\n---\n")

    for protocol_data in yaml_files_content:
        try:
            jsonschema.validate(instance=protocol_data, schema=schema)
            yaml_string = yaml.dump(protocol_data, indent=2, sort_keys=False, default_flow_style=False)
            md_yaml_block = f"```yaml\n{yaml_string}\n```\n"
            final_content.append(md_yaml_block)
            final_content.append("\n---\n")
        except jsonschema.ValidationError as e:
            print(f"Warning: Schema validation failed for a protocol: {e.message}", file=sys.stderr)

    return "\n".join(final_content)
