
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightIMPLIESleftPLUSleftWITHrightNOTBANGATOM BANG IMPLIES LPAREN NOT PLUS RPAREN WITH\n    formula : formula IMPLIES formula\n            | formula WITH formula\n            | formula PLUS formula\n    \n    formula : NOT formula\n            | BANG formula\n    \n    formula : LPAREN formula RPAREN\n    \n    formula : ATOM\n    '

_lr_action_items = {'NOT':([0,2,3,4,6,7,8,],[2,2,2,2,2,2,2,]),'BANG':([0,2,3,4,6,7,8,],[3,3,3,3,3,3,3,]),'LPAREN':([0,2,3,4,6,7,8,],[4,4,4,4,4,4,4,]),'ATOM':([0,2,3,4,6,7,8,],[5,5,5,5,5,5,5,]),'$end':([1,5,9,10,12,13,14,15,],[0,-7,-4,-5,-1,-2,-3,-6,]),'IMPLIES':([1,5,9,10,11,12,13,14,15,],[6,-7,-4,-5,6,6,-2,-3,-6,]),'WITH':([1,5,9,10,11,12,13,14,15,],[7,-7,-4,-5,7,7,-2,7,-6,]),'PLUS':([1,5,9,10,11,12,13,14,15,],[8,-7,-4,-5,8,8,-2,-3,-6,]),'RPAREN':([5,9,10,11,12,13,14,15,],[-7,-4,-5,15,-1,-2,-3,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,2,3,4,6,7,8,],[1,9,10,11,12,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> formula IMPLIES formula','formula',3,'p_formula_binary','pda_parser.py',74),
  ('formula -> formula WITH formula','formula',3,'p_formula_binary','pda_parser.py',75),
  ('formula -> formula PLUS formula','formula',3,'p_formula_binary','pda_parser.py',76),
  ('formula -> NOT formula','formula',2,'p_formula_unary','pda_parser.py',82),
  ('formula -> BANG formula','formula',2,'p_formula_unary','pda_parser.py',83),
  ('formula -> LPAREN formula RPAREN','formula',3,'p_formula_group','pda_parser.py',89),
  ('formula -> ATOM','formula',1,'p_formula_atom','pda_parser.py',95),
]
