import os
import glob
import json
import jsonschema
from rdflib import Graph

# --- Configuration ---
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PROTOCOLS_DIR = os.path.join(ROOT_DIR, "protocols")
SCHEMA_FILE = os.path.join(PROTOCOLS_DIR, "protocol.schema.json")
TARGET_FILE = os.path.join(ROOT_DIR, "AGENTS.md")
KNOWLEDGE_GRAPH_FILE = os.path.join(ROOT_DIR, "knowledge_core", "protocols.ttl")


DISCLAIMER = """\
# ---
# DO NOT EDIT THIS FILE DIRECTLY.
# This file is programmatically generated by the `protocol_compiler.py` script.
# All changes to agent protocols must be made in the source files
# located in the `protocols/` directory.
#
# This file contains the compiled protocols in a human-readable Markdown format,
# with machine-readable JSON definitions embedded.
# ---

"""

def load_schema():
    """Loads the protocol JSON schema."""
    try:
        with open(SCHEMA_FILE, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Error: Schema file not found at {SCHEMA_FILE}")
        return None
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from schema file at {SCHEMA_FILE}")
        return None

def compile_protocols():
    """
    Reads all .protocol.json and corresponding .protocol.md files from the
    protocols directory, validates them, and compiles them into two artifacts:
    1. A human-readable AGENTS.md file.
    2. A machine-readable knowledge graph in Turtle format (`.ttl`).
    """
    print("--- Starting Protocol Compilation (Markdown + Knowledge Graph) ---")
    print(f"Source directory: {PROTOCOLS_DIR}")
    print(f"Target AGENTS.md file: {TARGET_FILE}")
    print(f"Target Knowledge Graph file: {KNOWLEDGE_GRAPH_FILE}")


    schema = load_schema()
    if not schema:
        return

    # Find all source files of different types
    protocol_files = sorted(glob.glob(os.path.join(PROTOCOLS_DIR, "*.protocol.json")))
    md_files = glob.glob(os.path.join(PROTOCOLS_DIR, "*.protocol.md"))
    autodoc_files = glob.glob(os.path.join(PROTOCOLS_DIR, "*.autodoc.md"))

    # Combine all file types into a single list and sort them numerically
    all_files = sorted(protocol_files + autodoc_files)

    if not all_files:
        print("Error: No protocol or autodoc files found.")
        return

    print(f"Found {len(protocol_files)} protocol, {len(md_files)} markdown, and {len(autodoc_files)} autodoc files.")

    # Initialize RDF graph and start building AGENTS.md content
    g = Graph()
    final_content = [DISCLAIMER]

    # Process each file
    for file_path in all_files:
        base_name = os.path.basename(file_path)
        print(f"  - Processing {base_name}...")

        if file_path.endswith(".autodoc.md"):
            # This is a placeholder to inject auto-generated documentation
            doc_path = os.path.join(ROOT_DIR, "knowledge_core", "SYSTEM_DOCUMENTATION.md")
            try:
                with open(doc_path, "r") as f:
                    final_content.append(f.read())
                print(f"    - Injected system documentation from {doc_path}")
            except FileNotFoundError:
                print(f"    - Warning: System documentation file not found at {doc_path}")
            final_content.append("\n---\n")
            continue

        # --- Standard .protocol.json processing ---
        prefix = base_name.split("_")[0]
        matching_md = next((md for md in md_files if os.path.basename(md).startswith(prefix + "_")), None)

        if matching_md:
            print(f"    - Found corresponding markdown: {os.path.basename(matching_md)}")
            with open(matching_md, "r") as f:
                final_content.append(f.read())
        else:
            print(f"    - Warning: No corresponding markdown file found for prefix '{prefix}'.")

        # --- Validate and append JSON protocol content ---
        try:
            with open(file_path, "r") as f:
                protocol_data = json.load(f)
            jsonschema.validate(instance=protocol_data, schema=schema)
            print(f"    - JSON validation successful.")

            # --- Knowledge Graph Generation ---
            # Create a copy for JSON-LD processing to not modify the original dict
            protocol_data_for_ld = protocol_data.copy()
            # The context path is relative to the `protocols` directory
            protocol_data_for_ld["@context"] = "protocol.context.jsonld"
            # The publicID needs to be the directory where the file lives, so relative paths in the JSON-LD can be resolved
            base_uri = "file://" + os.path.abspath(PROTOCOLS_DIR) + "/"
            g.parse(data=json.dumps(protocol_data_for_ld), format="json-ld", publicID=base_uri)
            print(f"    - Parsed {base_name} into knowledge graph.")


            # --- AGENTS.md Generation ---
            json_string = json.dumps(protocol_data, indent=2)
            md_json_block = f"```json\n{json_string}\n```\n"
            final_content.append(md_json_block)

        except Exception as e:
            print(f"    - Error: Failed to process JSON for {base_name}: {e}")

        final_content.append("\n---\n")


    # --- Finalize and Write Outputs ---

    # Write the final AGENTS.md content
    with open(TARGET_FILE, "w") as f:
        f.write("\n".join(final_content))
    print("\n--- AGENTS.md Compilation Successful ---")
    print(f"Successfully generated new AGENTS.md file.")

    # Write the knowledge graph
    try:
        g.serialize(destination=KNOWLEDGE_GRAPH_FILE, format="turtle")
        print("\n--- Knowledge Graph Compilation Successful ---")
        print(f"Successfully generated knowledge graph at {KNOWLEDGE_GRAPH_FILE}")
    except Exception as e:
        print(f"\n--- Knowledge Graph Compilation Failed ---")
        print(f"Error serializing RDF graph: {e}")


def main():
    """Main function to run the compiler."""
    compile_protocols()

if __name__ == "__main__":
    main()