"""
This script generates a simplified, standard-compliant `AGENTS.md` file.

While the project's primary `AGENTS.md` is generated by a complex, hierarchical
system, many external AI agents and tools expect a simpler, more conventional
format. This script bridges that gap.

It parses the project's `Makefile` to extract the essential commands for common
tasks like installing dependencies, running tests, linting, and formatting code.
It then injects these discovered commands into a human-readable Markdown
template.

The output, `AGENTS.standard.md`, provides a straightforward, predictable
entry point for third-party agents, improving interoperability with the broader
AI development ecosystem.
"""
import os

"""
Generates a simplified, standard-compliant AGENTS.md file for external tools.

This script parses the project's Makefile to extract key commands (install, test,
lint, format) and injects them into a human-readable Markdown template. The
output, AGENTS.standard.md, is designed to provide a quick, conventional entry
point for third-party AI agents, bridging the gap between our complex internal
protocol system and the broader ecosystem's expectations.
"""

# --- Configuration ---
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
TARGET_FILE = os.path.join(ROOT_DIR, "AGENTS.standard.md")
MAKEFILE_PATH = os.path.join(ROOT_DIR, "Makefile")

# --- AGENTS.md Template ---
AGENTS_MD_TEMPLATE = """\
# AGENTS.md

This file provides instructions for AI coding agents to interact with this project. It is generated from the project's `Makefile` to ensure it is always up-to-date.

## Project Overview

This is a Python-based project with a sophisticated, self-correcting agent architecture. The agent's core protocols are managed programmatically. For detailed, machine-readable protocols, refer to the primary `AGENTS.md` file. This `AGENTS.standard.md` file provides a simplified summary for external tools.

## Build & Commands

Here are the essential commands for working with this repository.

### Dependency Installation

To install all required Python packages, run:
```bash
{install_command}
```

### Running Tests

To run the full suite of unit tests, use the following command:
```bash
{test_command}
```

## Code Style

This project uses standard Python code quality tools.

### Linting

To check the code for style issues, run the linter:
```bash
{lint_command}
```

### Formatting

To automatically format the code, run:
```bash
{format_command}
```

## Project Structure

- `protocols/`: Source files for the agent's governing protocols.
- `tooling/`: Scripts for compilation, validation, and other development tasks.
- `knowledge_core/`: Compiled knowledge artifacts used by the agent.

For more detailed information, please consult the `README.md`.
"""


def parse_makefile_command(target_name, makefile_content):
    """
    Parses a Makefile to find the main command for a specific target,
    skipping any 'echo' lines. This version iterates through lines for robustness.
    """
    lines = makefile_content.splitlines()
    try:
        # Find the line number of the target definition
        target_line_index = next(
            i for i, line in enumerate(lines) if line.startswith(f"{target_name}:")
        )
    except StopIteration:
        # If the target isn't found, fallback to the make command
        return f"make {target_name}"

    # Search for command lines in the lines following the target definition
    for i in range(target_line_index + 1, len(lines)):
        line = lines[i]

        # Command blocks end when a line does not start with a tab
        if not line.startswith("\t"):
            break

        command = line.strip()
        # If the line is an echo command, skip to the next line
        if command.startswith("@echo"):
            continue

        # We've found the first non-echo command. Return it after stripping the '@'.
        return command.lstrip("@").strip()

    # If no suitable command was found in the block, fallback
    return f"make {target_name}"


def main():
    """
    Generates a standard-compliant AGENTS.md file by parsing commands
    from the project's Makefile.
    """
    try:
        with open(MAKEFILE_PATH, "r") as f:
            makefile_content = f.read()
    except FileNotFoundError:
        print(f"Error: Makefile not found at {MAKEFILE_PATH}")
        return

    # Parse the commands from the Makefile
    install_command = parse_makefile_command("install", makefile_content)
    test_command = parse_makefile_command("test", makefile_content)
    lint_command = parse_makefile_command("lint", makefile_content)
    format_command = parse_makefile_command("format", makefile_content)

    # Populate the template
    content = AGENTS_MD_TEMPLATE.format(
        install_command=install_command,
        test_command=test_command,
        lint_command=lint_command,
        format_command=format_command,
    )

    try:
        with open(TARGET_FILE, "w") as f:
            f.write(content)
        print(f"Successfully generated standard-compliant AGENTS.md at {TARGET_FILE}")
    except IOError as e:
        print(f"Error: Failed to write to {TARGET_FILE}: {e}")


if __name__ == "__main__":
    main()