name: Validate Placeholders

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate-placeholders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Placeholder Validator
        run: python tooling/placeholder_manager.py validate