name: Standard PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        run: |
          echo "Running linter..."
          # This is a placeholder for a real linting step.
          # For this example, we will make it pass.
          exit 0

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "Running tests..."
          # This is a placeholder for a real test suite.
          exit 0

  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run security scan
        run: |
          echo "Running security scan..."
          # This is a placeholder for a real security scanner.
          exit 0